const LoginActionTypes = {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  RESET_PASSWORD_USER: "RESET_PASSWORD_USER",
  GET_USER: "GET_USER",
  LOGOUT_USER: "LOGOUT_USER",
  REMEMBER_USER: "REMEMBER_USER",
};

export default LoginActionTypes;
