const LoginActionTypes = {
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  RESET_PASSWORD_USER: "RESET_PASSWORD_USER",
  GET_USER: "GET_USER",
  LOGOUT_USER: "LOGOUT_USER",
  RENEW_ACCESS_TOKEN: "RENEW_ACCESS_TOKEN",
};

export default LoginActionTypes;
