const DeviceActionTypes = {
  LOAD_TABLE: "LOAD_TABLE",
  SELECT_ROW: "SELECT_ROW",
  GROUP_TABLE: "GROUP_TABLE",
  CHANGE_LOADING: "CHANGE_LOADING",
  COUNT_DEVICES: "COUNT_DEVICES",
  ADD_MODAL_DATA:"ADD_MODAL_DATA",
  REMOVE_MODAL_DATA:"REMOVE_MODAL_DATA"
};

export default DeviceActionTypes;
