const LiveViewActionTypes = {
  GET_SRC: "GET_SRC",
  GET_GROUP: "GET_GROUP",
  SET_WINDOWS: "SET_WINDOWS",
  SET_ORGANIZATION: "SET_ORGANIZATION",
  SET_VIDEO_PLAYER: "SET_VIDEO_PLAYER",
  SET_HEADER_VIDEO: "SET_HEADER_VIDEO",
  HIDE_HEADER_VIDEO: "HIDE_HEADER_VIDEO",
  SET_VIEW: "SET_VIEW",
  ADD_VIEW: "ADD_VIEW",
  ADD_VIDEO: "ADD_VIDEO",
  REMOVE_VIDEO: "REMOVE_VIDEO",
  REMOVE_ALL_VIDEO: "REMOVE_ALL_VIDEO",
  CHANGE_ASPECTRATIO: "CHANGE_ASPECTRATIO",
  CHANGE_STREAM: "CHANGE_STREAM",
  ADD_ASPECT_VIDEO: "ADD_ASPECT_VIDEO",
  ADD_ASPECT_VIDEO_ONE: "ADD_ASPECT_VIDEO_ONE",
};

export default LiveViewActionTypes;
