const PlaybackActionTypes = {
  CHECK_CAMERA: "CHECK_CAMERA",
  REF_PLAYBACK: "REF_PLAYBACK",
  ADD_VIDEO_PLAYBACK: "ADD_VIDEO_PLAYBACK",
  CUT_PLAYBACK: "CUT_PLAYBACK",
  CUT_TIME_PLAYBACK: "CUT_TIME_PLAYBACK",
  REMOVE_VIDEO_PLAY_BACK: "REMOVE_VIDEO_PLAY_BACK",
  REMOVE_ALL_VIDEO_PLAY_BACK: "REMOVE_ALL_VIDEO_PLAY_BACK",
  ASPECT_VIDEO_PLAY_BACK: "ASPECT_VIDEO_PLAY_BACK",
  DISABLE_DATE: "DISABLE_DATE",
  ACTIVE_DATE: "ACTIVE_DATE",
  ADD_DURATION_PLAYBACK: "ADD_DURATION_PLAYBACK",
  LOADING_PLAYBACK: "LOADING_PLAYBACK",
  LOADING_ERROR_PLAYBACK: "LOADING_ERROR_PLAYBACK",
  LOADING_VIDEO_PLAYBACK: "LOADING_VIDEO_PLAYBACK",
  CAMERA_ID: "CAMERA_ID",
  HEADER_VIDEO_PLAY_BACK: "HEADER_VIDEO_PLAY_BACK",
  HIDE_HEADER_VIDEO_PLAY_BACK: "HIDE_HEADER_VIDEO_PLAY_BACK",
};

export default PlaybackActionTypes;
